### ISSUE TITLE
Move device definitions to separate config files

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#145]
The device definitions should be moved out of libmbp since they are configuration, not code. I'm thinking to use YAML for the source files and then convert them to either JSON or a properties file during the build. That way, the source files remain readable and libmbp/mbtool don't need to include a heavyweight YAML parser. The converter tool can also validate the source files to ensure they are in the correct format.

With this change, we can stop adding all the additional `ro.patcher.*` and `ro.multiboot.*` lines in `/default`, which aren't even valid Android properties (they are far too long). mbtool can just read the device config file directly.

---

An example device config YAML file for `jflte` might look like this:

```yaml
---
name: Samsung Galaxy S 4 (Qcom)
id: jflte
codenames:
  # Regular variant
  - jflte
  - jflteatt
  - jfltecan
  - jfltecri
  - jfltecsp
  - jflterefreshspr
  - jfltespr
  - jfltetmo
  - jflteusc
  - jfltevzw
  - jfltexx
  - jfltezm
  # Active variant
  - jactivelte
  # Google Edition variant
  - jgedlte
  # GT-I9507
  - jftddxx
  # GT-I9515
  - jfvelte
  - jfveltexx

block_devs:
  base_dirs:
    - /dev/block/platform/msm_sdcc.1/by-name
  system:
    - /dev/block/platform/msm_sdcc.1/by-name/system
    - /dev/block/mmcblk0p16
  cache:
    - /dev/block/platform/msm_sdcc.1/by-name/cache
    - /dev/block/mmcblk0p18
  data:
    - /dev/block/platform/msm_sdcc.1/by-name/userdata
    - /dev/block/mmcblk0p29
  boot:
    - /dev/block/platform/msm_sdcc.1/by-name/boot
    - /dev/block/mmcblk0p20
  recovery:
    - /dev/block/platform/msm_sdcc.1/by-name/recovery
    - /dev/block/mmcblk0p21
  extra:
    - /dev/block/platform/msm_sdcc.1/by-name/aboot

boot_ui:
  supported: true
  flags:
    - TW_PREFER_LCD_BACKLIGHT
    - TW_HAS_DOWNLOAD_MODE
  graphics_backends:
    - fbdev

crypto:
  supported: true
  header_path: footer
```
